language: python
python:
  - "3.4"
  - "3.5"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coverage

# command to run tests
script: python manage.py test --settings=derb.test_settings

env:
#  - DJANGO_VERSION=1.9.11
  - DJANGO_VERSION=1.10.3

services:
  - postgresql

services:
  - memcached

addons:
  postgresql: "9.4"

after_success:
  - bash <(curl -s https://codecov.io/bash)
